sudo: required
services:
  - docker
jobs:
  include:
      # unit tests
    - stage: tests
      name: Unit Tests
      script:
        - docker build -f Dockerfile.dev -t testing/react-scapes .
        - docker run -e CI=true testing/react-scapes npm run test

      # development deploy
    - stage: deploy+development
      script: echo "Deploy placeholder development"
      if: branch = development

      # staging deploy
    - stage: deploy+production
      script: echo "Deploy placeholder staging"
      if: branch = staging

      # production deploy
    - stage: deploy+production
      script: echo "Deploy placeholder production"
      if: branch = master
branches:
  only:
    - master
    - development
