sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t testing/react-scapes .
jobs:
  include:
    - stage: tests
      name: Unit Tests
      script: docker run -e CI=true testing/react-scapes npm run test
    - stage: deploy
      script: echo "Deploy placeholder"
      if: branch = master
branches:
  only:
    - master
    - development
